# Generated by Django 5.2.7 on 2026-09-20 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='complaint',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='complaints.complaint'),
        ),
        migrations.RunSQL(  # _tidb_fk_patch
            sql="ALTER TABLE communications_message ADD CONSTRAINT communications_message_complaint_id_fk FOREIGN KEY (complaint_id) REFERENCES complaints_complaint (id)",
            reverse_sql="ALTER TABLE communications_message DROP FOREIGN KEY communications_message_complaint_id_fk",
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunSQL(  # _tidb_fk_patch
            sql="ALTER TABLE communications_message ADD CONSTRAINT communications_message_sender_id_fk FOREIGN KEY (sender_id) REFERENCES accounts_user (id)",
            reverse_sql="ALTER TABLE communications_message DROP FOREIGN KEY communications_message_sender_id_fk",
        ),
    ]
