"""
Django settings for crims project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
import sys
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.module_loading import import_string

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

_dotenv_path = BASE_DIR / '.env'
if _dotenv_path.exists():
    for _line in _dotenv_path.read_text().splitlines():
        _line = _line.strip()
        if not _line or _line.startswith('#') or '=' not in _line:
            continue
        _k, _v = _line.split('=', 1)
        os.environ.setdefault(_k.strip(), _v.strip().strip("'").strip('"'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

def _require_secret_key():
    """Root cause of the audit finding
    ---------------------------------
    SECRET_KEY previously fell back to a hard-coded literal that was committed
    to git. Anyone with read access to the repository could forge session
    cookies, password-reset tokens and any signed value, and rotating the key
    never invalidated anything because the committed fallback kept working.

    The application now refuses to boot without an explicit secret.
    """
    key = os.environ.get('SECRET_KEY')
    if key:
        return key

    # In tests Django supplies its own throwaway key.
    if 'test' in sys.argv:
        return 'django-insecure-test-only-secret-key'

    raise ImproperlyConfigured(
        'SECRET_KEY is not set. Generate one with:\n'
        '    python -c "from django.core.management.utils import '
        'get_random_secret_key; print(get_random_secret_key())"\n'
        'and add it to your environment (Vercel env var, .env, or CI secret).'
    )


SECRET_KEY = _require_secret_key()

DEBUG = os.environ.get('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1,.vercel.app,.vercel.sh,.fly.dev').split(',')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

if not DEBUG and 'test' not in sys.argv:
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'complaints',
    'officers',
    'investigations',
    'evidence',
    'suspects',
    'witnesses',
    'reports',
    'notifications',
    'analytics_dashboard',
    'ai_engine',
    'communications',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'crims.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'notifications.context_processors.notification_count',
                'accounts.context_processors.approver_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'crims.wsgi.application'

# ---------------------------------------------------------------------------
# Administrator invitations
# ---------------------------------------------------------------------------
# Only these accounts may invite administrators or approve admin accounts.
#
# The role check alone is deliberately NOT enough: `role='admin'` is a value
# in a database column, and relying on "whoever is an admin" would make the
# set of people who can mint further admins implicit and invisible. Naming the
# addresses makes it reviewable and rotatable without a code change.
#
# Bootstrap caveat: an approver must already hold `role='admin'`. If none of
# these addresses does yet, the first one has to be created out of band.
ADMIN_APPROVER_EMAILS = [
    address.strip().lower()
    for address in os.environ.get(
        'ADMIN_APPROVER_EMAILS', 'solankimihir1210@gmail.com'
    ).split(',')
    if address.strip()
]


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'crims_db'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', ''),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '3306'),
    }
}

_db_url = os.environ.get('DATABASE_URL') or os.environ.get('JAWSDB_URL')
if _db_url:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(default=_db_url, conn_max_age=600)
    # Managed MySQL hosts like TiDB Cloud enforce TLS.
    if (
        DATABASES['default'].get('ENGINE') == 'django.db.backends.mysql'
        and 'tidbcloud' in str(DATABASES['default'].get('HOST', ''))
    ):
        import certifi
        DATABASES['default'].setdefault('OPTIONS', {})['ssl'] = {'ca': certifi.where()}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTH_USER_MODEL = 'accounts.User'

# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]
# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
LOGOUT_REDIRECT_URL = 'home'

EMAIL_VERIFICATION_REQUIRED = os.environ.get(
    "EMAIL_VERIFICATION_REQUIRED", "true"
).lower() in ("1", "true", "yes", "on")

def _auto_email_backend():
    """Pick a transport from whichever credentials happen to be present."""
    if os.environ.get('GMAIL_OAUTH_CLIENT_ID') and os.environ.get(
        'GMAIL_REFRESH_TOKEN'
    ):
        return 'accounts.email_backend.GmailOAuthBackend'
    if EMAIL_HOST_USER and EMAIL_HOST_PASSWORD:
        return 'django.core.mail.backends.smtp.EmailBackend'
    return 'django.core.mail.backends.console.EmailBackend'


# An explicit EMAIL_BACKEND wins over the guess above.
#
# This exists because the OAuth credentials are Vercel *secrets*: they cannot
# be read back, so deleting one to force a different transport is a one-way
# door. Naming the transport outright makes the choice reversible and
# reviewable. Gmail's OAuth refresh token also expires, and this is how the
# deployment is moved off it without deleting anything.
def _resolve_email_backend(explicit):
    """An explicit EMAIL_BACKEND wins over the automatic guess."""
    return (explicit or '').strip() or _auto_email_backend()


EMAIL_BACKEND = _resolve_email_backend(os.environ.get('EMAIL_BACKEND'))

# MAILERS = {
#     'default': {
#         'BACKEND': 'django.core.mail.backends.console.EmailBackend',
#     },
# }


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

STATIC_ROOT = BASE_DIR / 'staticfiles'

# ---------------------------------------------------------------------------
# Logging (added: LOGGING was `{}`, so production errors were invisible)
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
        'plain': {
            'format': '{levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': os.environ.get('LOG_LEVEL', 'INFO'),
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            # Records 4xx/5xx (including PermissionDenied) with a stack trace.
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        'django.security': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': False,
        },
        'crims': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# ---------------------------------------------------------------------------
# Upload limits (added: no per-file cap existed on any FileField)
# ---------------------------------------------------------------------------

# 25 MB is the largest accepted evidence file; the global ceiling is set a
# little higher to leave room for multipart framing.
DATA_UPLOAD_MAX_MEMORY_SIZE = 26 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 5 * 1024 * 1024

# ---------------------------------------------------------------------------
# Email resilience
# ---------------------------------------------------------------------------

# Root cause of the production outage found in the audit: the Gmail OAuth
# refresh token expired (HTTP 401), and `send_otp_email` let the exception
# escape, so `POST /register/` returned HTTP 500 *and* left an orphaned,
# un-verifiable user row behind. accounts.utils.send_otp_email now catches
# delivery failures and the register view surfaces a form error instead.
EMAIL_FAIL_SILENTLY = False

# ---------------------------------------------------------------------------
# Session / cookie hardening
# ---------------------------------------------------------------------------

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'
# Age out idle sessions so an unattended police workstation does not keep a
# live session indefinitely.
SESSION_COOKIE_AGE = 60 * 60 * 8
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# ---------------------------------------------------------------------------
# Media storage
# ---------------------------------------------------------------------------
#
# Root cause of the production finding
# -----------------------------------
# `MEDIA_ROOT` is the local filesystem, and Vercel's filesystem is ephemeral
# and read-only outside the build. `/media/` returned 404 in production, so
# evidence uploads, suspect photos and ID documents were all unreachable.
#
# On Vercel the project must use a real object store. Set MEDIA_STORAGE to
# django-storages S3 (or any django-storages backend) via the environment; it
# is configured below and activated automatically when MEDIA_STORAGE is set.
# Locally it falls back to the filesystem.

# The hashed manifest backend needs a populated staticfiles/ directory, which
# does not exist during `manage.py test`, so tests fall back to plain static
# storage (otherwise every {% static %} raises "Missing staticfiles manifest").
_RUNNING_TESTS = 'test' in sys.argv

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if DEBUG or _RUNNING_TESTS
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# django-storages reads these from Django settings, not from os.environ, so
# they have to be forwarded explicitly for an S3-compatible store to work.
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'auto')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL', '')
# R2 and other S3-compatible stores reject the per-object ACL headers that
# django-storages sends by default, which surfaces as a confusing 400.
AWS_DEFAULT_ACL = None

if os.environ.get('MEDIA_STORAGE'):
    STORAGES['default'] = {
        'BACKEND': os.environ['MEDIA_STORAGE'],
        'OPTIONS': {
            'endpoint_url': AWS_S3_ENDPOINT_URL,
            'default_acl': None,
        },
    }
    # A storage backend that fails to import takes down every request, so the
    # deployment is verified to import before it is trusted.
    from django.core.exceptions import ImproperlyConfigured

    try:
        import_string(os.environ['MEDIA_STORAGE'])
    except (ImportError, AttributeError) as exc:
        raise ImproperlyConfigured(
            'MEDIA_STORAGE={!r} could not be loaded: {}. Add the package that '
            'provides it to requirements.txt.'.format(
                os.environ['MEDIA_STORAGE'], exc,
            )
        )


# ---------------------------------------------------------------------------
# CSRF trusted origins
# ---------------------------------------------------------------------------
#
# Behind Vercel the request Host is the deployment domain. Django compares the
# Origin header against this list; without it, every POST is rejected with 403
# on a custom domain. Comma-separated via the environment, e.g.
#   CSRF_TRUSTED_ORIGINS=https://crims.example.com,https://crims-eta.vercel.app
_extra_origins = os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [
    origin.strip()
    for origin in _extra_origins.split(',')
    if origin.strip()
]

# ---------------------------------------------------------------------------
# Health check
# ---------------------------------------------------------------------------
# Used by the deployment checklist / uptime monitoring. Reports only whether
# the database answers - never any configuration detail.
