# Generated by Django 5.2.7 on 2026-10-01 10:58

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaint_category_alter_complaint_citizen_and_more'),
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suspect',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.validators.suspect_photo_path),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['wanted'], name='suspects_su_wanted_48a9fd_idx'),
        ),
        migrations.AddIndex(
            model_name='suspect',
            index=models.Index(fields=['complaint'], name='suspects_su_complai_339057_idx'),
        ),
    ]
