# Generated by Django 5.2.7 on 2026-09-20 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('theft', 'Theft'), ('cybercrime', 'Cyber Crime'), ('fraud', 'Fraud'), ('assault', 'Assault'), ('other', 'Other')], max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('incident_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('investigation', 'Investigation Started'), ('evidence', 'Evidence Collection'), ('resolved', 'Resolved')], default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tracking_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('priority', models.CharField(default='Medium', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('ai_category', models.CharField(blank=True, max_length=100, null=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
