# Generated by Django 5.2.7 on 2026-09-20 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        ('suspects', '0001_initial'),
        ('witnesses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='suspects',
            field=models.ForeignKey(blank=True, null=True, db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='suspects.suspect'),
        ),
        migrations.RunSQL(  # _tidb_fk_patch
            sql="ALTER TABLE complaints_complaint ADD CONSTRAINT complaints_complaint_suspects_id_fk FOREIGN KEY (suspects_id) REFERENCES suspects_suspect (id)",
            reverse_sql="ALTER TABLE complaints_complaint DROP FOREIGN KEY complaints_complaint_suspects_id_fk",
        ),
        migrations.AddField(
            model_name='complaint',
            name='witnesses',
            field=models.ManyToManyField(blank=True, related_name='complaints', to='witnesses.witness'),
        ),
    ]
