# Generated by Django 5.2.7 on 2026-09-30 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
        ('suspects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='suspects',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='suspects.suspect'),
        ),
    ]
