# Generated by Django 5.2.7 on 2026-10-01 10:58

import accounts.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidencecustody',
            options={'ordering': ['-transferred_at']},
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_evidence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to=accounts.validators.evidence_upload_path),
        ),
        migrations.AlterField(
            model_name='evidencecustody',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidence_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='evidencecustody',
            index=models.Index(fields=['evidence', '-transferred_at'], name='evidence_ev_evidenc_c0a958_idx'),
        ),
    ]
